swagger: "2.0"
info:
  title: Animal API
  description: API for managing animals
  version: 1.0.0
host: localhost:8080
schemes:
  - http
paths:
  /files/uploads:
    post:
      summary: Upload file content
      consumes:
        - text/csv
        - application/xml
      description: Uploads file content in CSV or XML format.
      parameters:
        - in: body
          name: animals
          description: animals to upload to db
          schema:
            type: string
            example: |
              Name,Type,Sex,Weight,Cost
              Buddy,cat,female,41,78
            

        - in: header
          name: Content-Type
          required: true
          schema:
            type: string

      responses:
        '201':
          description: File content successfully uploaded
          schema:
            type: string
            example: >-
              Created or [Field error in object 'animal' on field 'name': rejected value []; codes [name.required.animal.name,name.required.name,name.required.java.lang.String,name.required];

      tags:
        - Animals
  /animals:
    get:
      tags:
        - Animals
      summary: Get animals
      description: Returns a list of animals based on provided filters and sorting options
      parameters:
        - name: type
          in: query
          description: Filter by animal type
          type: string
          example: dog
        - name: category
          in: query
          description: Filter by animal category
          type: string
          example: "1"
        - name: sex
          in: query
          description: Filter by animal sex
          type: string
          example: male
        - name: sortBy
          in: query
          description: Sort by specified fields and orders
          type: array
          items:
            type: string
          collectionFormat: multi
          example: ["weight:asc", "category:desc"]
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/AnimalDocument'

definitions:
  AnimalDocument:
    type: object
    properties:
      name:
        type: string
      type:
        type: string
      sex:
        type: string
      weight:
        type: integer
      cost:
        type: integer
      category:
        type: integer

tags:
  - name: Animals
    description: Operations related to animals
